const helper = require("./helpers");
const parkNameList = 
[
    "Denali National Park & Preserve",
    "Gates Of The Arctic National Park & Preserve",
    "Glacier Bay National Park & Preserve",
    "Katmai National Park & Preserve",
    "Kenai Fjords National Park",
    "Kobuk Valley National Park",
    "Lake Clark National Park & Preserve",
    "Wrangell - St Elias National Park & Preserve",
    "Crater Lake National Park",
    "Mount Rainier National Park",
    "North Cascades National Park",
    "Olympic National Park",
    "Channel Isl&s National Park",
    "Death Valley National Park",
    "Joshua Tree National Park",
    "Sequoia & Kings Canyon National Parks",
    "Lassen Volcanic National Park",
    "Pinnacles National Park",
    "Redwood National & State Parks",
    "Yosemite Yosemite National Park",
    "Arches National Park",
    "Big Bend National Park",
    "Bryce Canyon National Park",
    "Canyonl&s National Park",
    "Capitol Reef National Park",
    "Carlsbad Caverns National Park",
    "Gr& Canyon National Park",
    "Great Basin National Park",
    "Guadalupe Mountains National Park",
    "Petrified Forest National Park",
    "Saguaro National Park",
    "White S&s National Park",
    "Zion National Park",
    "Black Canyon Of The Gunnison National Park",
    "Gr& Teton National Park",
    "Great S& Dunes National Park & Preserve",
    "Glacier National Park",
    "Mesa Verde National Park",
    "Rocky Mountain National Park",
    "Yellowstone National Park",
    "Acadia National Park",
    "Badl&s National Park",
    "Cuyahoga Valley National Park",
    "Gateway Arch National Park",
    "Hot Springs National Park",
    "Indiana Dunes National Park",
    "Isle Royale National Park",
    "Theodore Roosevelt National Park",
    "Voyageurs National Park",
    "Wind Cave National Park",
    "Biscayne National Park",
    "Congaree National Park",
    "Dry Tortugas National Park",
    "Everglades National Park",
    "Great Smoky Mountains National Park",
    "Mammoth Cave National Park",
    "Shen&oah National Park",
    "New River Gorge National Park & Preserve",
    "Haleakalā National Park",
    "Hawaiʻi Volcanoes National Park",
    "Virgin Isl&s National Park"
];

module.exports = {
    parkNameList
}