const parkNameList = 
[
    "Denali National Park & Preserve",
    "Gates Of The Arctic National Park & Preserve",
    "Glacier Bay National Park & Preserve",
    "Katmai National Park & Preserve",
    "Kenai Fjords National Park",
    "Kobuk Valley National Park",
    "Lake Clark National Park & Preserve",
    "Wrangell - St Elias National Park & Preserve",
    "Crater Lake National Park",
    "Mount Rainier National Park",
    "North Cascades National Park",
    "Olympic National Park",
    "Channel Islands National Park",
    "Death Valley National Park",
    "Joshua Tree National Park",
    "Sequoia & Kings Canyon National Parks",
    "Lassen Volcanic National Park",
    "Pinnacles National Park",
    "Redwood National and State Parks",
    "Yosemite",
    "Arches",
    "Big Bend",
    "Bryce Canyon",
    "Canyonlands",
    "Capitol Reef",
    "Carlsbad Caverns",
    "Grand Canyon",
    "Great Basin",
    "Guadalupe Mountains",
    "Petrified Forest",
    "Saguaro",
    "White Sands",
    "Zion",
    "Black Canyon",
    "Grand Teton",
    "Great Sand Dunes",
    "Glacier National Park",
    "Mesa Verde",
    "Rocky Mountain",
    "Yellowstone",
    "Acadia",
    "Badlands",
    "Cuyahoga Valley",
    "Gateway Arch",
    "Hot Springs",
    "Indiana Dunes",
    "Isle Royale",
    "Theodore Roosevelt",
    "Voyageurs",
    "Wind Cave",
    "Biscayne",
    "Congaree",
    "Dry Tortugas",
    "Everglades",
    "Great Smoky Mountain",
    "Mammoth Cave",
    "Shenandoah",
    "New River Gorge",
    "Haleakala",
    "Hawai'i Volcanoes",
    "America Samoa",
    "Virgin Islands",
];

const helper = require("./helpers")
const usersInfos = [
    ['mike', 'xixi@gmail.com','2022-12-01',helper.hashPassword('Feng@fpl1997'),"What is your mother's first name?",'Ying','What is your born city?',"Beijing"],
    ['John', 'xixi@gmail.com','2022-12-01',helper.hashPassword('Feng@fpl1997'),"What is your mother's first name?",'Ying','What is your born city?',"Beijing"],
    ['wendy', 'xixi@gmail.com','2022-12-01',helper.hashPassword('Feng@fpl1997'),"What is your mother's first name?",'Ying','What is your born city?',"Beijing"],
    ['jack', 'xixi@gmail.com','2022-12-01',helper.hashPassword('Feng@fpl1997'),"What is your mother's first name?",'Ying','What is your born city?',"Beijing"],
    ['nick', 'xixi@gmail.com','2022-12-01',helper.hashPassword('Feng@fpl1997'),"What is your mother's first name?",'Ying','What is your born city?',"Beijing"],
] 

module.exports = {
    parkNameList,
    usersInfos,
}